// File: server/tests/http_teach_debug_marker.rs
// Purpose: Verifies the server injects (or withholds) the sb-debug meta tag
//          correctly and that both HTML pages carry the required DOM structure.
//          Sprint 8: updated assertions for Variation A session-root layout;
//          removed static #mute/#video-off/#hangup checks (now dynamic via session-ui.js).
// Last updated: Sprint 9 (2026-04-19) -- self-check, lobby-toast, chat-drawer script tag asserts

mod common;

use common::{spawn_app, spawn_app_with, TestOpts};
use singing_bridge_server::http::security_headers::EXPECTED_CSP;

#[tokio::test]
async fn test_dev_teach_html_carries_debug_marker_student_view() {
    let app = spawn_app().await;
    let cookie = app.signup_teacher("teacher@test.example", "myroom").await;
    // Student view: no cookie
    let (status, headers, body) = app.get_html("/teach/myroom", None).await;
    assert_eq!(status, reqwest::StatusCode::OK);
    assert!(headers.contains_key("content-security-policy"));
    assert_eq!(
        headers.get("content-security-policy").unwrap().to_str().unwrap(),
        EXPECTED_CSP
    );
    assert!(
        body.contains(r#"<meta name="sb-debug""#),
        "dev student view missing sb-debug meta tag"
    );
    assert!(
        !body.contains("<!-- sb:debug -->"),
        "dev student view still has placeholder"
    );

    // Sprint 8: session UI mounts into #session-root (static controls are generated by JS)
    assert!(body.contains(r#"id="session-root""#), "student.html missing #session-root");

    // Sprint 8: session-ui.js and theme.css must be loaded
    assert!(
        body.contains(r#"src="/assets/session-ui.js""#),
        "student.html missing session-ui.js"
    );
    assert!(
        body.contains(r#"href="/assets/theme.css""#),
        "student.html missing theme.css"
    );

    // Sprint 8: no Google Fonts URLs (fonts are self-hosted)
    assert!(
        !body.contains("fonts.googleapis.com"),
        "student.html must not reference Google Fonts"
    );
    assert!(
        !body.contains("fonts.gstatic.com"),
        "student.html must not reference Google Fonts CDN"
    );

    // Sprint 8: mobile viewport meta is present (student is responsive)
    assert!(
        body.contains(r#"name="viewport""#),
        "student.html missing viewport meta tag"
    );

    // Landing-page gating notices (student-only).
    assert!(body.contains(r#"id="block-notice""#), "student.html missing #block-notice");
    assert!(body.contains(r#"id="degraded-notice""#), "student.html missing #degraded-notice");

    // Sprint 4: quality badge + reconnect banner + floor violation notice (still present outside session-root).
    assert!(body.contains(r#"id="quality-badge""#), "student.html missing #quality-badge");
    assert!(body.contains(r#"id="reconnect-banner""#), "student.html missing #reconnect-banner");
    assert!(body.contains(r#"id="floor-violation""#), "student.html missing #floor-violation");

    // Sprint 4: new script tags for adapt/quality/reconnect/session-core loaded in order.
    let adapt_idx = body.find(r#"src="/assets/adapt.js""#).expect("student.html missing adapt.js");
    let quality_idx = body.find(r#"src="/assets/quality.js""#).expect("student.html missing quality.js");
    let reconnect_idx = body.find(r#"src="/assets/reconnect.js""#).expect("student.html missing reconnect.js");
    let sessioncore_idx = body.find(r#"src="/assets/session-core.js""#).expect("student.html missing session-core.js");
    let signalling_idx = body.find(r#"src="/assets/signalling.js""#).expect("student.html missing signalling.js");
    assert!(adapt_idx < quality_idx, "adapt.js must load before quality.js");
    assert!(quality_idx < reconnect_idx, "quality.js must load before reconnect.js");
    assert!(reconnect_idx < sessioncore_idx, "reconnect.js must load before session-core.js");
    assert!(sessioncore_idx < signalling_idx, "session-core.js must load before signalling.js");

    // session-ui.js must load before signalling.js (it provides window.sbSessionUI)
    let session_ui_idx = body.find(r#"src="/assets/session-ui.js""#).expect("student.html missing session-ui.js");
    assert!(session_ui_idx < signalling_idx, "session-ui.js must load before signalling.js");

    // Sprint 9: new script tags present and load order maintained.
    let self_check_idx = body.find(r#"src="/assets/self-check.js""#).expect("student.html missing self-check.js");
    let lobby_toast_idx = body.find(r#"src="/assets/lobby-toast.js""#).expect("student.html missing lobby-toast.js");
    let chat_drawer_idx = body.find(r#"src="/assets/chat-drawer.js""#).expect("student.html missing chat-drawer.js");
    let panels_idx = body.find(r#"src="/assets/session-panels.js""#).expect("student.html missing session-panels.js");
    assert!(chat_drawer_idx < session_ui_idx, "chat-drawer.js must load before session-ui.js");
    assert!(panels_idx < session_ui_idx, "session-panels.js must load before session-ui.js");
    // self-check and lobby-toast just need to be present before session scripts.
    let _ = self_check_idx;
    let _ = lobby_toast_idx;

    // Sprint 9: legacy static elements removed — assert their IDs are absent.
    assert!(
        !body.contains(r#"id="lobby-message-banner""#),
        "student.html must not contain legacy #lobby-message-banner"
    );
    assert!(
        !body.contains(r#"id="chat-panel""#),
        "student.html must not contain legacy #chat-panel"
    );

    drop(cookie);
    app.shutdown().await;
}

#[tokio::test]
async fn test_dev_teach_html_carries_debug_marker_teacher_view() {
    let app = spawn_app().await;
    let cookie = app.signup_teacher("teacher@test.example", "myroom").await;
    // Teacher view: authenticated cookie
    let (status, headers, body) = app.get_html("/teach/myroom", Some(&cookie)).await;
    assert_eq!(status, reqwest::StatusCode::OK);
    assert!(headers.contains_key("content-security-policy"));
    assert!(
        body.contains(r#"<meta name="sb-debug""#),
        "dev teacher view missing sb-debug meta tag"
    );
    assert!(
        !body.contains("<!-- sb:debug -->"),
        "dev teacher view still has placeholder"
    );

    // Sprint 8: session UI mounts into #session-root
    assert!(body.contains(r#"id="session-root""#), "teacher.html missing #session-root");

    // Sprint 8: session-ui.js and theme.css must be loaded
    assert!(
        body.contains(r#"src="/assets/session-ui.js""#),
        "teacher.html missing session-ui.js"
    );
    assert!(
        body.contains(r#"href="/assets/theme.css""#),
        "teacher.html missing theme.css"
    );

    // Sprint 8: no Google Fonts
    assert!(
        !body.contains("fonts.googleapis.com"),
        "teacher.html must not reference Google Fonts"
    );
    assert!(
        !body.contains("fonts.gstatic.com"),
        "teacher.html must not reference Google Fonts CDN"
    );

    // Sprint 4: quality badge + reconnect banner + floor violation notice.
    assert!(body.contains(r#"id="quality-badge""#), "teacher.html missing #quality-badge");
    assert!(body.contains(r#"id="reconnect-banner""#), "teacher.html missing #reconnect-banner");
    assert!(body.contains(r#"id="floor-violation""#), "teacher.html missing #floor-violation");

    // Sprint 4: script load order must match student.html.
    let t_adapt = body.find(r#"src="/assets/adapt.js""#).expect("teacher.html missing adapt.js");
    let t_quality = body.find(r#"src="/assets/quality.js""#).expect("teacher.html missing quality.js");
    let t_reconnect = body.find(r#"src="/assets/reconnect.js""#).expect("teacher.html missing reconnect.js");
    let t_sessioncore = body.find(r#"src="/assets/session-core.js""#).expect("teacher.html missing session-core.js");
    let t_signalling = body.find(r#"src="/assets/signalling.js""#).expect("teacher.html missing signalling.js");
    assert!(t_adapt < t_quality, "teacher: adapt.js must load before quality.js");
    assert!(t_quality < t_reconnect, "teacher: quality.js must load before reconnect.js");
    assert!(t_reconnect < t_sessioncore, "teacher: reconnect.js must load before session-core.js");
    assert!(t_sessioncore < t_signalling, "teacher: session-core.js must load before signalling.js");

    let t_session_ui = body.find(r#"src="/assets/session-ui.js""#).expect("teacher.html missing session-ui.js");
    assert!(t_session_ui < t_signalling, "teacher: session-ui.js must load before signalling.js");

    // Sprint 9: teacher gets self-check and chat-drawer; chat-drawer before session-ui.
    let t_self_check = body.find(r#"src="/assets/self-check.js""#).expect("teacher.html missing self-check.js");
    let t_chat_drawer = body.find(r#"src="/assets/chat-drawer.js""#).expect("teacher.html missing chat-drawer.js");
    let t_panels = body.find(r#"src="/assets/session-panels.js""#).expect("teacher.html missing session-panels.js");
    assert!(t_chat_drawer < t_session_ui, "teacher: chat-drawer.js must load before session-ui.js");
    assert!(t_panels < t_session_ui, "teacher: session-panels.js must load before session-ui.js");
    let _ = t_self_check;

    // Sprint 9: legacy static chat panel removed from teacher.html.
    assert!(
        !body.contains(r#"id="chat-panel""#),
        "teacher.html must not contain legacy #chat-panel"
    );

    app.shutdown().await;
}

#[tokio::test]
async fn test_prod_teach_html_has_no_debug_marker() {
    let app = spawn_app_with(TestOpts { dev: false, ..Default::default() }).await;
    let cookie = app.signup_teacher("teacher@test.example", "myroom").await;
    let (status, headers, body) = app.get_html("/teach/myroom", None).await;
    assert_eq!(status, reqwest::StatusCode::OK);
    assert!(headers.contains_key("content-security-policy"));
    assert_eq!(
        headers.get("content-security-policy").unwrap().to_str().unwrap(),
        EXPECTED_CSP
    );
    assert!(
        !body.contains("<!-- sb:debug -->"),
        "prod view must not serve the sb:debug placeholder comment"
    );
    assert!(
        !body.contains(r#"<meta name="sb-debug" content="1""#),
        "prod view must not carry the injected meta tag"
    );
    // Sprint 8: session-root and quality elements present in prod too.
    assert!(body.contains(r#"id="session-root""#), "prod student view missing #session-root");
    assert!(body.contains(r#"id="quality-badge""#), "prod student view missing #quality-badge");
    assert!(body.contains(r#"id="reconnect-banner""#), "prod student view missing #reconnect-banner");
    assert!(body.contains(r#"id="floor-violation""#), "prod student view missing #floor-violation");
    // No Google Fonts in prod either.
    assert!(!body.contains("fonts.googleapis.com"), "prod view must not reference Google Fonts");
    drop(cookie);
    app.shutdown().await;
}
